# ============================================================
# Kitty Configuration
# ============================================================

# ----- Font -----
font_family             Hack
font_size               12
modify_font cell_height 120%

# ----- Behavior -----
cursor_shape            beam
cursor_blink_interval   0.5
confirm_os_window_close 0
background_opacity      0.75

# ----- Scrollback -----
scrollback_lines 10000

# ----- Sound Efect -----
enable_audio_bell no

# ----- Shell -----
shell_integration enabled

# ----- Theme -----
include ~/.config/kitty/skwd-theme.conf