foreground            #fadbd9
background            #1f0f0e
selection_foreground  #68000c
selection_background  #ffb3ae
url_color             #ffb870
cursor                #ffb3ae
cursor_text_color     #68000c

color0   #1f0f0e
color1   #ffb4ab
color2   #ffb3ae
color3   #ffb870
color4   #ffb3ae
color5   #ffb870
color6   #a76200
color7   #fadbd9

color8   #ac8886
color9   #ffb4ab
color10  #ffb3ae
color11  #ffb870
color12  #ffb3ae
color13  #ffb870
color14  #a76200
color15  #fadbd9

tab_bar_background              #1f0f0e
tab_bar_margin_color            #1f0f0e
active_tab_foreground           #68000c
active_tab_background           #ffb3ae
inactive_tab_foreground         #e5bdba
inactive_tab_background         #1f0f0e
