general {
    col.active_border = rgb(${color.primary})
    col.inactive_border = rgb(${color.surface})
}

decoration {
    col.shadow = rgba(${color.shadow})
}

input {
    col.cursor = rgb(${color.primary})
}
